info:
  name: Anemon
  firstname: Vincent
  number: "+33 42 42 42 42 42"
  mail: vincent.anemon@example.com
  github: https://github.com/anemon
  linkedin: https://www.linkedin.com/anemon

variante:
  webDev:
    - "API"
    - "backend"
  Hacker:
    - "Optimized"
    - "Security"

